language: python
python:
  - "3.6"
  - "3.8"
before_install:
  - sudo apt-get -y install socat
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - ./test.sh
  - python setup.py flake8
